export const TEXT_INPUT_MINIMUM_CHARACTER_LIMIT = 3;
export const ZERO = 0;


export const CHANGE_VALUE_OF_SEARCH_INPUT = "SEARCH_INPUT/CHANGE_VALUE";
export const FETCH_ALL_JOBS_FROM_API_INIT = "JOBS_API/FETCH_INIT";
export const FETCH_ALL_JOBS_FROM_API_SUCCESS = "JOBS_API/FETCH_SUCCESS";
export const FETCH_ALL_JOBS_FROM_API_FAILURE = "JOBS_API/FETCH_FAILURE";
export const CLEAR_RESULT_LIST = "RESULT_LIST/CLEAR";